name: Deploy to GitHub Pages

on:
  schedule:
    - cron: "0 3 * * *"  # daily at 03:00 UTC
  workflow_dispatch:  # allow manual trigger
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go-scraper/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        working-directory: go-scraper
        run: go mod download

      - name: Build scraper
        working-directory: go-scraper
        run: go build ./cmd/scraper

      - name: Build static site generator
        working-directory: go-scraper
        run: go build ./cmd/static-site

      - name: Run scraper
        working-directory: go-scraper
        env:
          LOG_LEVEL: INFO
          DB_PATH: ../data/jobs.db
        run: ./scraper --config ../config/scraper_config.json --out ../data/job_applications.csv

      - name: Generate static site
        working-directory: go-scraper
        env:
          LOG_LEVEL: INFO
          DB_PATH: ../data/jobs.db
        run: ./static-site --out ../public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
